# Generated by Django 5.0.4 on 2024-10-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.ManyToManyField(blank=True, to='blog.tag'),
        ),
    ]
