# Generated by Django 5.0.4 on 2024-12-26 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_alter_post_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
